baseURL = 'http://flirn.github.io/'
languageCode = 'de-DE'
title = 'Fabian Schwarze'
theme = 'hugo-book'
Copyright = "© Fabian Schwarze 2022"
[params]
    BookToC = false
    BookSearch = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
